name: Post welcome comment

on:
  pull_request:
    types: [opened, closed]

permissions:
  pull-requests: write

jobs:
  manage-comments:
    runs-on: ubuntu-latest
    steps:
      - name: Release-specific welcome
        if: github.event.action == 'opened' && startsWith(github.head_ref, 'releases/')
        run: gh pr comment "$PR_URL" --body "The head of this PR starts with 'releases/'"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Default welcome
        if: github.event.action == 'opened' && !startsWith(github.head_ref, 'releases/')
        run: gh pr comment "$PR_URL" --body "Welcome to the repository!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}

      - name: Merged goodbye
        if: github.event.pull_request.merged == true
        run: gh pr comment "$PR_URL" --body "The PR was merged!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
